### ISSUE TITLE
few samples can stably detect retrieval heads?

### ISSUE THREAD

**Issue by ZetangForward** [nightdessert/Retrieval_Head#2]
Hi, thank you for the outstanding work. I observed in your repository the statement "we found that only a few samples can stably detect retrieval heads." Could you please clarify whether the experimental results (Figure 4) presented in your paper were derived from experiments conducted on the following dataset: https://github.com/nightdessert/Retrieval_Head/blob/main/haystack_for_detect/needles.jsonl?

**Comment by nightdessert** [comment]
> Hi, thank you for the outstanding work. I observed in your repository the statement "we found that only a few samples can stably detect retrieval heads." Could you please clarify whether the experimental results (Figure 4) presented in your paper were derived from experiments conducted on the following dataset: https://github.com/nightdessert/Retrieval_Head/blob/main/haystack_for_detect/needles.jsonl?

What I mean is that, using few samples can detect some of the strongest retrieval heads, because they are irrelevant to the context. For a more rigorous probing and measuring  of all the attention heads, we need detect on more contexts. Figure 4 is a  rigorous detection results on three sets of (needle, haystack) all ranging from 0-50K.

**Comment by nightdessert** [comment]
> Hi, thank you for the outstanding work. I observed in your repository the statement "we found that only a few samples can stably detect retrieval heads." Could you please clarify whether the experimental results (Figure 4) presented in your paper were derived from experiments conducted on the following dataset: https://github.com/nightdessert/Retrieval_Head/blob/main/haystack_for_detect/needles.jsonl?

Thanks for this question anyway, I have clarified it in readme.

**Comment by ZetangForward** [comment]
> > Hi, thank you for the outstanding work. I observed in your repository the statement "we found that only a few samples can stably detect retrieval heads." Could you please clarify whether the experimental results (Figure 4) presented in your paper were derived from experiments conducted on the following dataset: https://github.com/nightdessert/Retrieval_Head/blob/main/haystack_for_detect/needles.jsonl?
> 
> Thanks for this question anyway, I have clarified it in readme.

ok, thanks for your clarify.
