### ISSUE TITLE
Empty JSON Files in results/graph/llama-2-7b-80k.zip

### ISSUE THREAD

**Issue by DseidLi** [nightdessert/Retrieval_Head#6]
<img width="756" alt="image" src="https://github.com/user-attachments/assets/3a6ff023-f4a2-45b0-81f8-44fe3bb9fb0e">
I noticed that all the JSON files in the results/graph/llama-2-7b-80k.zip file are empty after unzipping. Is this an oversight, or are these files intended for format demonstration purposes?

**Comment by lemonsweetie** [comment]
same question

**Comment by nlokeshiisc** [comment]
Hi, I also tried to reproduce the code. I downloaded the Llama-2-7b-80k model from huggingface and tried computing the retrieval scores. The head score jsons are empty, and the reason I see is that none of the needle in haystack testcases achieve the rogue score > 50. Could you please help me debug the issue.
